export const petsObjects = [
	{
		id: 0,
		nombre: "Collar Unisex Cuero bordado color turquesa",
		precio: 35,
		tipo: "Collar",
		imagen: "/media/pictures/images-merchandising/resized/image-collar-bordado.png",
	},
	{
		id: 1,
		nombre: "Collar Cuero 100% con agarrador",
		precio: 40,
		tipo: "Collar",
		imagen: "/media/pictures/images-merchandising/resized/image-collar-cuero.png",
	},
	{
		id: 2,
		nombre: "Collar Metal Rock color negro",
		precio: 37,
		tipo: "Collar",
		imagen: "/media/pictures/images-merchandising/resized/image-collar-pinchos.png",
	},
	{
		id: 3,
		nombre: "Pienso Natural para Perros",
		precio: 13.5,
		tipo: "Pienso",
		imagen: "/media/pictures/images-merchandising/resized/image-natural-dog-food.png",
	},
	{
		id: 4,
		nombre: "Pienso Vegano para Gatos",
		precio: 17,
		tipo: "Pienso",
		imagen: "/media/pictures/images-merchandising/resized/image-natural-cat-food.png",
	},
	{
		id: 5,
		nombre: "Pienso ecologico para Conejos",
		precio: 12,
		tipo: "Pienso",
		imagen: "/media/pictures/images-merchandising/resized/image-natural-rabbit-food.png",
	},
	{
		id: 6,
		nombre: "Identificador Luxury con brillantes para Perros",
		precio: 36,
		tipo: "Identificador Mascota",
		imagen: "/media/pictures/images-merchandising/resized/image-dog-id-tag.png",
	},
	{
		id: 7,
		nombre: "Identificador Plata con Incrustaciones para Gatos",
		precio: 27,
		tipo: "Identificador Mascota",
		imagen: "/media/pictures/images-merchandising/resized/image-cat-id-tag.png",
	},
	{
		id: 8,
		nombre: "Comedero Luxury unisex blanco de ceramica",
		precio: 15,
		tipo: "Comedero",
		imagen: "/media/pictures/images-merchandising/resized/image-dog-feeder.png",
	},
	{
		id: 9,
		nombre: "Comedero Artesano unisex de ceramica",
		precio: 22,
		tipo: "Comedero",
		imagen: "/media/pictures/images-merchandising/resized/image-dog-feeder-orange.png",
	},
	{
		id: 10,
		nombre: "Comedero Luxury rojo Metalico",
		precio: 18,
		tipo: "Comedero",
		imagen: "/media/pictures/images-merchandising/resized/image-cat-feeder.png",
	},
	{
		id: 11,
		nombre: "Mordedor Goma Verde para Perros",
		precio: 16,
		tipo: "Juguete",
		imagen: "/media/pictures/images-merchandising/resized/image-dog-toy-green.png",
	},
	{
		id: 12,
		nombre: "Juguete Goma Amarilla para Gatos",
		precio: 14,
		tipo: "Juguete",
		imagen: "/media/pictures/images-merchandising/resized/image-cat-toy-yellow.png",
	},
	{
		id: 13,
		nombre: "Cama de terciopelo color Tuquesa",
		precio: 34,
		tipo: "Cama",
		imagen: "/media/pictures/images-merchandising/resized/image-pet-bed-white.png",
	},
	{
		id: 14,
		nombre: "Cama de terciopelo color Verde",
		precio: 32,
		tipo: "Cama",
		imagen: "/media/pictures/images-merchandising/resized/image-pet-bed-green.png",
	},
	{
		id: 15,
		nombre: "Cama de terciopelo color Azul",
		precio: 36,
		tipo: "Cama",
		imagen: "/media/pictures/images-merchandising/resized/image-pet-bed-blue.png",
	},
	{
		id: 16,
		nombre: "Identificador Bola de pinchos",
		precio: 21,
		tipo: "Idenficador",
		imagen: "media/pictures/images-merchandising/resized/image-dog-id-tag-spikeball.png",
	},
	{
		id: 17,
		nombre: "Identificador Casa de perro",
		precio: 18,
		tipo: "Idenficador",
		imagen: "media/pictures/images-merchandising/resized/image-dog-id-tag-doggy-house.png",
	},
	{
		id: 18,
		nombre: "Identificador Galleta para perros",
		precio: 22,
		tipo: "Idenficador",
		imagen: "media/pictures/images-merchandising/resized/image-dog-id-tag-biscuit.png",
	},
	{
		id: 19,
		nombre: "Identificador Chapa militar Canina",
		precio: 24,
		tipo: "Idenficador",
		imagen: "media/pictures/images-merchandising/resized/image-dog-id-tag-military.png",
	},
	{
		id: 20,
		nombre: "Identificador Bola mundo",
		precio: 20,
		tipo: "Idenficador",
		imagen: "media/pictures/images-merchandising/resized/image-dog-id-tag-world.png",
	},
	{
		id: 21,
		nombre: "Ropa Deportiva perro Color Rojo",
		precio: 42,
		tipo: "Ropa",
		imagen: "media/pictures/images-merchandising/resized/image-dog-red-cloth.png",
	},
	{
		id: 22,
		nombre: "Ropa Deportiva Militar desierto Perro",
		precio: 45,
		tipo: "Ropa",
		imagen: "media/pictures/images-merchandising/resized/image-dog-desert-military-cloth.png",
	},
];
